apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: inference-cluster-dev
  region: us-east-1
addons:
  - name: aws-efs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
#availabilityZones:
#- us-east-1a
#- us-east-1b
#- us-east-1c
#- us-east-1d
managedNodeGroups:
  - name: cpu-workers
    instanceType: m5.xlarge
    minSize: 0
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 512
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/inference-cluster-dev: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      allow: true
      publicKeyName: fine-tuning-key
  - name: gpu-workers
    instanceType: g5.xlarge
    minSize: 0
    maxSize: 5
    desiredCapacity: 1
    privateNetworking: true
    amiFamily: bottlerocket
    volumeSize: 1024
    taints:
      - key: "nvidia.com/gpu"
        value: ""
        effect: "NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/inference-cluster-dev: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true