apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama-service
spec:
  serveConfigV2: |
    applications:
      - name: llama_app
        import_path: llama_service:app
        route_prefix: /
        deployments:
          - name: llama_deployment
            num_replicas: auto
            max_ongoing_requests: 5
            autoscaling_config:
              min_replicas: 1
              max_replicas: 5
              target_ongoing_requests: 2
            ray_actor_options:
              num_gpus: 1
        runtime_env:
          working_dir: "https://github.com/coloryourlife/ray-test/blob/28b65039a1c18cdfcffc84ce325d61d285f9dc2f/project.zip"
          pip: ["transformers", "torch"]
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.9.0
            env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            resources:
              limits:
                cpu: "2"
                memory: "8Gi"
              requests:
                cpu: "2"
                memory: "8Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
    workerGroupSpecs:
      - groupName: gpu-worker-group
        replicas: 1
        rayStartParams: {}
        template:
          spec:
            tolerations:
              - key: "ray.io/node-type"
                operator: "Equal"
                value: "worker"
                effect: "NoSchedule"
            containers:
            - name: ray-worker
              image: rayproject/ray:2.9.0
              env:
                - name: HF_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_api_token
              resources:
                limits:
                  cpu: "3.5"
                  memory: "14Gi"
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "3.5"
                  memory: "14Gi"
                  nvidia.com/gpu: "1"
